application: albumblr
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  login: admin
  secure: optional
  script: admin.py

- url: /.*
  script: albumblr.py
